export const sample_foods: any[] = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Meatball",
    price: 20,
    cookTime: "20-30",
    favorite: true,
    origins: ["Persia", "Middle East", "China"],
    stars: 4.7,
    imageUrl: "assets/food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    id: "3",
    name: "Hamburger",
    price: 5,
    cookTime: "10-15",
    favorite: false,
    origins: ["Germany", "US"],
    stars: 3.5,
    imageUrl: "assets/food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    id: "4",
    name: "Fried Potatoes",
    price: 2,
    cookTime: "15-20",
    favorite: true,
    origins: ["Belgium", "France"],
    stars: 3.3,
    imageUrl: "assets/food-4.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    id: "5",
    name: "Chicken Soup",
    price: 11,
    cookTime: "40-50",
    favorite: false,
    origins: ["India", "Asia"],
    stars: 3.0,
    imageUrl: "assets/food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    id: "6",
    name: "Vegetables Pizza",
    price: 9,
    cookTime: "40-50",
    favorite: false,
    origins: ["Italy"],
    stars: 4.0,
    imageUrl: "assets/food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 4 },
  { name: "Lunch", count: 4 },
  { name: "SlowFood", count: 4 },
  { name: "Hamburger", count: 4 },
  { name: "Fry", count: 4 },
  { name: "Soup", count: 4 },
];

export const sample_users: any[] = [
  {
    name: "Pradnya Chavan",
    email: "pradnya.c@girmesofttech.com",
    password: "12345",
    address: "Mahadevnagar, Manjri",
    isAdmin: true,
  },
  {
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Mahadevnagar, Manjri",
    isAdmin: false,
  },
];
